---
- name: Install some packages
  ansible.builtin.yum:
    name:
      - vim
      - wget
      - bash-completion
      - tree
      - git
      - podman
      # for installing newer python
      - "@Development tools"
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - xz
      - xz-devel
      - libffi-devel
      - findutils
      - tk-devel
    state: latest
  become: true
  tags:
    - yum

# Install gh cli
# https://github.com/cli/cli/blob/trunk/docs/install_linux.md#fedora-centos-red-hat-enterprise-linux-dnf

- name: Ensure hosts file is there with localhost in it
  ansible.builtin.lineinfile:
    path: ~/hosts
    line: localhost
    create: yes

- name: Template default python version for pyenv
  ansible.builtin.template:
    src: .python-version.j2
    dest: ~/.python-version

- name: Template .ansible-navigator.yml
  ansible.builtin.template:
    src: .ansible-navigator.yml.j2
    dest: ~/.ansible-navigator.yml

- name: Make dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/vimtmp
    - ~/.azure
    - ~/tmp
  tags:
    - config_files

- name: Copy over files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest | default('~/') }}"
    mode: "{{ item.mode | default(omit) }}"
    backup: yes
  with_items:
    - src: ~/.ansible.cfg
    - src: ~/.azure/credentials
      dest: ~/.azure/credentials
    - src: .bashrc
    - src: .bash_profile
    - src: .gitconfig
    - src: .inputrc
    - src: ~/Documents/git/ansible-azure-mgmt/tools/load_credentials.sh
    - src: ~/.ssh/id_rsa
      dest: ~/.ssh/id_rsa
      mode: "0400"
    - src: ~/.ssh/id_rsa.pub
      dest: ~/.ssh/id_rsa.pub
    - src: .vimrc
  tags:
    - config_files

- name: Ensure hosts file is set in .ansible.cfg
  ansible.builtin.lineinfile:
    path: ~/.ansible.cfg
    regexp: '^inventory      ='
    line: inventory      = ~/hosts
    create: yes

- name: Check for pyenv
  ansible.builtin.command:
    cmd: which pyenv
  register: pyenv
  ignore_errors: yes
  changed_when: false

- name: Install pyenv
  block:
    - name: Run installer
      ansible.builtin.shell: curl https://pyenv.run | bash

    # Need to set export TMPDIR=~/tmp because /tmp has noexec
    - name: Install python
      ansible.builtin.shell: pyenv install "{{ python_version }}"
      environment:
        TMPDIR: /home/{{ ansible_user_id }}/tmp

    - name: Add venv
      ansible.builtin.shell: pyenv virtualenv "{{ python_version }}" "{{ python_version }}"_dev
  when: pyenv.rc != 0

# Separately update pip first to ensure it's up to date before any other pip installs
- name: Update pip
  ansible.builtin.pip:
    name:
      - pip
      - setuptools
    state: latest
    # extra_args: --user
    virtualenv: "~/.pyenv/versions/{{ python_version }}/envs/{{ python_version }}_dev"
    virtualenv_command: pyenv
  tags:
    - pip

- name: Pip install things
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-navigator
      - ansible-lint
      # - thefuck
    state: latest
    # extra_args: --user
    virtualenv: "~/.pyenv/versions/{{ python_version }}/envs/{{ python_version }}_dev"
    virtualenv_command: pyenv
  tags:
    - pip

- name: Galaxy install collection azure.azcollection
  community.general.ansible_galaxy_install:
    type: collection
    name: azure.azcollection
  tags:
    - galaxy

- name: Pip install azure.azcollection requirements
  ansible.builtin.pip:
    requirements: ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
    virtualenv: "~/.pyenv/versions/{{ python_version }}/envs/{{ python_version }}_dev"
    virtualenv_command: pyenv
  tags:
    - pip

# Destination name must be set to a full path, not a dir and be empty the first time
- name: Clone personal SRE repo
  ansible.builtin.git:
    repo: git@github.com:{{ ansible_user_id }}/ansible-azure-sre.git
    dest: ~/ansible-azure-sre
    update: no
    accept_newhostkey: yes
  tags:
    - git

- name: Add remote upstream to github projects
  # Git module does not know how to add remotes (yet...)
  # Using command and silencing corresponding ansible-lint rule
  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: git remote add upstream git@github.com:ansible/ansible-azure-sre.git
    chdir: ~/ansible-azure-sre
  register: result
  changed_when: result.rc == 0
  failed_when:
    - result.rc != 0
    - result.stderr | default('') is not search("remote .* already exists")
  tags:
    - git

- name: Fetch all remotes
  ansible.builtin.command:
    cmd: git fetch --all
    chdir: ~/ansible-azure-sre
  register: result
  changed_when: false
  tags:
    - git

- name: Switch to upstream/main
  ansible.builtin.git:
    repo: git@github.com:ansible/ansible-azure-sre.git
    dest: ~/ansible-azure-sre
    remote: upstream
    version: upstream/main
  tags:
    - git

- name: Galaxy install collection redhat.ansible_azure_sre
  ansible.builtin.command:
    cmd: ansible-galaxy collection install .
    chdir: ~/ansible-azure-sre
  register: result
  changed_when: result.stdout is not search("Nothing to do")
  tags:
    - galaxy

- name: iterm2 shell integration
  ansible.builtin.get_url:
    url: https://iterm2.com/shell_integration/bash
    dest: "{{ item }}"
    mode: "0776"
  become: true
  with_items:
    - /root/.iterm2_shell_integration.bash
    - /home/{{ ansible_user_id }}/.iterm2_shell_integration.bash
  tags:
    - config_files

- name: Pull latest image
  containers.podman.podman_image:
    name: quay.io/aoc/ee-aap-azure-sre
    force: yes
